server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/junil/web-3-202210/library/library/upload/